# Generated by Django 4.2.6 on 2023-10-22 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserRecords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=64, unique=True)),
                ("gender", models.CharField(max_length=64)),
                ("age", models.IntegerField()),
                ("medical_conditions", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="VitalRecords",
            fields=[
                (
                    "vital_id",
                    models.CharField(
                        max_length=128, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("normal_range", models.CharField(max_length=32)),
                ("critical", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="UserVitalRecords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField(default=0.0)),
                ("timestamp", models.DateTimeField()),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vital_management_system.userrecords",
                        to_field="username",
                    ),
                ),
                (
                    "vital_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vital_management_system.vitalrecords",
                    ),
                ),
            ],
        ),
    ]
